
manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/lynnlee0522/zmk_offical.git  # 修改这里
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: st7789_screen  # 修改这里，指定分支名
      import: app/west.yml
  self:
    path: config